# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# This article was useful for the initial setup:
#   https://www.datacamp.com/community/tutorials/cd-package-docs-pkgdown-travis

language: r
r:
  - oldrel
  - release
  - devel

cache: packages

# These are not part of the default Travis VM and need to be installed
addons:
  apt:
    packages:
      - libharfbuzz-dev
      - libfribidi-dev
      - qpdf

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: main
